### ISSUE TITLE
Pagination: specifying page size?

### ISSUE THREAD

**Issue by hcayless** [distributed-text-services/specifications#97] opened 2018-05-16 13:08 UTC
Do we want to allow clients to modify page size for paginated collections? I think this should be up to the implementer whether they want to allow it, but that we should provide an optional parameter allowing the client to set page size in the specification.

**Comment by hcayless** [comment] 2018-05-24 14:35
Need to investigate what Hydra does and use that if it has a way to set page size.

**Comment by jonathanrobie** [comment] 2018-05-24 14:36
Let's use the Hydra mechanism for this if it exists.  If not, let's use the `size` parameter.

Feel free to close this after saying which mechanism is used and reflecting that in the document.

**Comment by jonathanrobie** [comment] 2018-06-07 13:14
Action item: Jonathan to research if there is a standard way to do this.

**Comment by PonteIneptique** [comment] 2020-10-09 13:14
I think this issue did not move since the last comment from @jonathanrobie 

We have a `?page` argument but not a `page_size`/`size` one.

**Comment by monotasker** [comment] 2024-03-08 16:15
We confirmed during the tech committee meeting on 2024-03-08 that we will not include a page size parameter in the specification. The size of page will be entirely up to the server. This is in order to support static implementations that cannot adjust response page sizes.

commit https://github.com/distributed-text-services/specifications/commit/a0db8ca0f5b9ef2e208baae7cacd8e2b6108685b
release https://github.com/distributed-text-services/specifications/releases/tag/1-alpha1

This is an alpha release and we are looking for feedback!

**Closed by monotasker** 2024-03-08 16:15 UTC
Labels: Question, Collection Endpoint
